begin;
create extension if not exists pgtap with schema extensions;
select plan(74);
select has_table('public', 'Ticket', 'Ticket table exists');
select has_table('public', 'TicketActivity', 'Activity table exists');
select has_table('public', 'TicketSyncOutbox', 'Outbox table exists');
select has_table('public', 'DiscordAccountLink', 'Discord account link table exists');
select has_table('public', 'TicketImage', 'Ticket image table exists');
select col_is_pk('public', 'Ticket', 'id', 'Ticket id is primary key');
select col_has_default('public', 'Ticket', 'publicId', 'Public ID has default');
select has_column('public', 'Ticket', 'priority', 'Ticket priority exists');
select col_not_null('public', 'Ticket', 'priority', 'Ticket priority is required');
select col_has_default('public', 'Ticket', 'priority', 'Ticket priority has a default');
select is((select count(*)::integer from pg_enum e join pg_type t on t.oid = e.enumtypid where t.typnamespace = 'public'::regnamespace and t.typname = 'TicketPriority'), 4, 'Ticket priority has four levels');
select has_trigger('public', 'Ticket', 'Ticket_set_updated_at', 'Updated-at trigger exists');
select is((select relrowsecurity from pg_class where oid = 'public."Ticket"'::regclass), true, 'Ticket RLS is enabled');
select is((select relrowsecurity from pg_class where oid = 'public."DiscordAccountLink"'::regclass), true, 'Discord account link RLS is enabled');
select is((select relrowsecurity from pg_class where oid = 'public."TicketImage"'::regclass), true, 'Ticket image RLS is enabled');
select is((select count(*)::integer from information_schema.role_table_grants where table_schema = 'public' and table_name = 'TicketImage' and grantee in ('anon', 'authenticated')), 0, 'Ticket images have no direct client grants');
select is((select public from storage.buckets where id = 'ticket-images'), false, 'Ticket image bucket is private');
select is((select file_size_limit::integer from storage.buckets where id = 'ticket-images'), 10485760, 'Ticket image bucket limits files to 10 MB');
select ok((select allowed_mime_types from storage.buckets where id = 'ticket-images') @> array['application/pdf', 'application/vnd.ms-excel', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'text/markdown', 'application/vnd.iccprofile', 'text/x-python'], 'Ticket attachment bucket allows documents');
select is((select count(*)::integer from information_schema.role_table_grants where table_schema = 'public' and table_name = 'DiscordAccountLink' and grantee = 'authenticated'), 0, 'Authenticated users have no direct link table grants');
select is((select count(*)::integer from information_schema.table_constraints where table_schema = 'public' and table_name = 'DiscordAccountLink' and constraint_type = 'UNIQUE'), 1, 'Discord user can only be linked once');
select is((select count(*)::integer from information_schema.table_constraints where table_schema = 'public' and table_name = 'DiscordAccountLink' and constraint_type = 'FOREIGN KEY'), 1, 'Link belongs to an auth user');
select has_table('public', 'AppUser', 'App user table exists');
select has_table('public', 'Team', 'Team table exists');
select has_table('public', 'TeamMembership', 'Team membership table exists');
select has_table('public', 'Kanban', 'Kanban table exists');
select has_table('public', 'KanbanTeam', 'Kanban team table exists');
select has_table('public', 'KanbanState', 'Kanban state table exists');
select has_table('public', 'KanbanTag', 'Kanban tag table exists');
select has_table('public', 'KanbanCard', 'Kanban card table exists');
select has_table('public', 'KanbanCardTag', 'Kanban card tag table exists');
select is((select relrowsecurity from pg_class where oid = 'public."Kanban"'::regclass), true, 'Kanban RLS is enabled');
select is((select count(*)::integer from information_schema.role_table_grants where table_schema = 'public' and table_name in ('AppUser', 'Team', 'TeamMembership', 'Kanban', 'KanbanTeam', 'KanbanState', 'KanbanTag', 'KanbanCard', 'KanbanCardTag') and grantee = 'authenticated'), 0, 'Kanban tables have no direct authenticated grants');
select is((select count(*)::integer from pg_publication_tables where pubname = 'supabase_realtime' and tablename = 'Ticket'), 1, 'Ticket is published to Realtime');
select is((select count(*)::integer from pg_enum e join pg_type t on t.oid = e.enumtypid where t.typnamespace = 'public'::regnamespace and t.typname = 'TicketStatus' and e.enumlabel = 'EN_STAGING'), 1, 'Ticket status includes staging');
select is((select count(*)::integer from pg_enum e join pg_type t on t.oid = e.enumtypid where t.typnamespace = 'public'::regnamespace and t.typname = 'Platform' and e.enumlabel = 'EXTERNO'), 1, 'Platform includes external tickets');
select lives_ok($$select public.create_ticket('Prueba', 'Detalle', 'BUG', null, 'WEB', 'pgTAP', 'test-user', null)$$, 'Atomic create RPC works');
select is((select priority::text from public."Ticket" where title = 'Prueba'), 'MEDIA', 'Legacy and existing tickets default to medium priority');
select lives_ok($$select public.create_ticket('Prioridad alta', 'Detalle', 'BUG', 'ALTA', null, 'WEB', 'pgTAP', 'priority-test-user', null)$$, 'Create RPC accepts priority');
select is((select priority::text from public."Ticket" where title = 'Prioridad alta'), 'ALTA', 'Create RPC persists priority');
select lives_ok($$select public.create_ticket_with_images(gen_random_uuid(), 'Prueba con imagen', 'Detalle', 'BUG', 'CRITICA', null, 'DISCORD', 'pgTAP', 'image-test-user', 'discord-user', '[{"id":"37a76303-632b-4bd6-a9c9-7f61f22c9bf1","storagePath":"ticket/image.png","fileName":"image.png","mimeType":"image/png","size":1024}]'::jsonb)$$, 'Atomic create with images RPC works');
select is((select priority::text from public."Ticket" where title = 'Prueba con imagen'), 'CRITICA', 'Create with images persists priority');
select is((select count(*)::integer from public."TicketImage" where "fileName" = 'image.png'), 1, 'Ticket image metadata is persisted');
select lives_ok($$select public.create_ticket_with_images(gen_random_uuid(), 'Prueba con documento', 'Detalle', 'REQUERIMIENTO', 'MEDIA', null, 'DISCORD', 'pgTAP', 'document-test-user', 'discord-user', '[{"id":"8c6a6ab5-2173-405f-9204-eea2ec1a0e11","storagePath":"ticket/document.xlsx","fileName":"document.xlsx","mimeType":"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","size":2048}]'::jsonb)$$, 'Atomic create with documents RPC works');
select is((select count(*)::integer from public."TicketImage" where "fileName" = 'document.xlsx'), 1, 'Ticket document metadata is persisted');
select lives_ok($$select public.create_ticket_with_images(gen_random_uuid(), 'Prueba con archivos técnicos', 'Detalle', 'REQUERIMIENTO', 'MEDIA', null, 'DISCORD', 'pgTAP', 'technical-file-test-user', 'discord-user', '[{"id":"cbbbdc2a-8c0b-4e30-bb2a-a1420e435336","storagePath":"ticket/display.icc","fileName":"display.icc","mimeType":"application/vnd.iccprofile","size":1024},{"id":"286d7858-b387-41d2-9fd7-95c5270910ba","storagePath":"ticket/script.py","fileName":"script.py","mimeType":"text/x-python","size":1024}]'::jsonb)$$, 'Atomic create with ICC and Python files works');
select is((select count(*)::integer from public."TicketImage" where "fileName" = 'display.icc'), 1, 'ICC metadata is persisted');
select is((select count(*)::integer from public."TicketImage" where "fileName" = 'script.py'), 1, 'Python metadata is persisted');
select is((select count(*)::integer from public."TicketActivity" where "actorId" = 'test-user'), 1, 'Create records activity atomically');
select is((select count(*)::integer from public."TicketSyncOutbox" o join public."Ticket" t on t."publicId" = o."ticketPublicId" where t.title = 'Prueba'), 1, 'Create enqueues Discord thread atomically');
select lives_ok($$select public.update_ticket((select "publicId" from public."Ticket" where title = 'Prueba'), '{"status":"EN_STAGING"}'::jsonb, 'WEB', 'pgTAP', 'test-user')$$, 'Ticket can move to staging');
select is((select status::text from public."Ticket" where title = 'Prueba'), 'EN_STAGING', 'Ticket persists staging status');
select like((select payload->>'content' from public."TicketSyncOutbox" o join public."Ticket" t on t."publicId" = o."ticketPublicId" where t.title = 'Prueba' and o.type = 'SEND_THREAD_MESSAGE' order by o."createdAt" desc limit 1), '%¡Entramos en la era de las pruebibas!%', 'Web status update uses the friendly Discord message');
select lives_ok($$select public.update_ticket((select "publicId" from public."Ticket" where title = 'Prueba'), '{"priority":"BAJA"}'::jsonb, 'WEB', 'pgTAP', 'test-user')$$, 'Ticket priority can be updated');
select is((select priority::text from public."Ticket" where title = 'Prueba'), 'BAJA', 'Ticket persists updated priority');
select lives_ok($$select public.update_ticket((select "publicId" from public."Ticket" where title = 'Prueba'), '{"platform":"NESTOR"}'::jsonb, 'WEB', 'pgTAP', 'test-user')$$, 'Ticket platform can be updated from web');
select is((select payload->>'syncControls' from public."TicketSyncOutbox" o join public."Ticket" t on t."publicId" = o."ticketPublicId" where t.title = 'Prueba' and o.type = 'SEND_THREAD_MESSAGE' order by o."createdAt" desc, o.id desc limit 1), 'true', 'Web platform update enqueues Discord controls synchronization');
select is(public.record_discord_interaction('interaction-1', 3), true, 'First interaction is recorded');
select is(public.record_discord_interaction('interaction-1', 3), false, 'Repeated interaction is deduplicated');
select lives_ok($$select public.retry_ticket_sync_job((select o.id from public."TicketSyncOutbox" o join public."Ticket" t on t."publicId" = o."ticketPublicId" where t.title = 'Prueba'), 'Discord 403', null, true)$$, 'Permanent retry is handled');
select is((select o.status::text from public."TicketSyncOutbox" o join public."Ticket" t on t."publicId" = o."ticketPublicId" where t.title = 'Prueba'), 'DEAD_LETTER', 'Permanent 4xx becomes dead letter');

insert into auth.users (id, instance_id, aud, role, email, encrypted_password, email_confirmed_at, raw_app_meta_data, raw_user_meta_data, created_at, updated_at)
values ('10000000-0000-0000-0000-000000000001', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', 'kanban-test@rial.local', '', now(), '{}'::jsonb, '{}'::jsonb, now(), now());
insert into public."AppUser" ("userId", role) values ('10000000-0000-0000-0000-000000000001', 'ADMIN');
insert into public."Team" (id, name) values ('20000000-0000-0000-0000-000000000001', 'Equipo Test');
insert into public."TeamMembership" (id, "teamId", "userId", role) values ('30000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000001', '10000000-0000-0000-0000-000000000001', 'LEADER');

select lives_ok($$select public.create_kanban('Kanban Test', array['20000000-0000-0000-0000-000000000001'::uuid], '10000000-0000-0000-0000-000000000001')$$, 'Kanban is created atomically');
select is((select count(*)::integer from public."KanbanState" s join public."Kanban" k on k.id = s."kanbanId" where k.name = 'Kanban Test' and s.status = 'ACTIVE'), 3, 'Kanban starts with three default states');
select is((select count(*)::integer from public."KanbanTeam" kt join public."Kanban" k on k.id = kt."kanbanId" where k.name = 'Kanban Test' and kt.status = 'ACTIVE'), 1, 'Kanban is assigned to its team');

insert into public."KanbanCard" (id, "kanbanId", title, description, "stateId", "assigneeUserId", "createdByUserId")
select '40000000-0000-0000-0000-000000000001', k.id, 'Tarjeta Test', repeat('Descripción extensa ', 500), s.id, '10000000-0000-0000-0000-000000000001', '10000000-0000-0000-0000-000000000001'
from public."Kanban" k join public."KanbanState" s on s."kanbanId" = k.id
where k.name = 'Kanban Test' and s.name = 'Por hacer';

select throws_ok($$select public.cancel_kanban_state((select "stateId" from public."KanbanCard" where id = '40000000-0000-0000-0000-000000000001'))$$, 'P0001', 'No puedes eliminar un estado que contiene tarjetas', 'State cancellation is blocked while it contains cards');
select throws_ok($$select public.cancel_kanban((select id from public."Kanban" where name = 'Kanban Test'))$$, 'P0001', 'No puedes eliminar un kanban que contiene tarjetas', 'Kanban cancellation is blocked while it contains cards');
select lives_ok($$update public."TeamMembership" set status = 'CANCELLED' where id = '30000000-0000-0000-0000-000000000001'$$, 'Membership can be cancelled');
select is((select "assigneeUserId"::text from public."KanbanCard" where id = '40000000-0000-0000-0000-000000000001'), '10000000-0000-0000-0000-000000000001', 'Cancelling membership preserves historical card assignment');
select lives_ok($$select public.cancel_kanban_card('40000000-0000-0000-0000-000000000001')$$, 'Card is soft deleted');
select lives_ok($$select public.cancel_kanban_state((select id from public."KanbanState" s join public."Kanban" k on k.id = s."kanbanId" where k.name = 'Kanban Test' and s.name = 'Por hacer'))$$, 'Empty state is soft deleted');
select lives_ok($$select public.cancel_kanban((select id from public."Kanban" where name = 'Kanban Test'))$$, 'Empty kanban is soft deleted');
select is((select status::text from public."Kanban" where name = 'Kanban Test'), 'CANCELLED', 'Kanban remains stored as cancelled');
select lives_ok($$select public.cancel_team('20000000-0000-0000-0000-000000000001')$$, 'Team is soft deleted');
select is((select status::text from public."Team" where id = '20000000-0000-0000-0000-000000000001'), 'CANCELLED', 'Team remains stored as cancelled');
select * from finish();
rollback;
