begin;
create extension if not exists pgtap with schema extensions;
select plan(18);
select has_table('public', 'Ticket', 'Ticket table exists');
select has_table('public', 'TicketActivity', 'Activity table exists');
select has_table('public', 'TicketSyncOutbox', 'Outbox table exists');
select col_is_pk('public', 'Ticket', 'id', 'Ticket id is primary key');
select col_has_default('public', 'Ticket', 'publicId', 'Public ID has default');
select has_trigger('public', 'Ticket', 'Ticket_set_updated_at', 'Updated-at trigger exists');
select is((select relrowsecurity from pg_class where oid = 'public."Ticket"'::regclass), true, 'Ticket RLS is enabled');
select is((select count(*)::integer from pg_publication_tables where pubname = 'supabase_realtime' and tablename = 'Ticket'), 1, 'Ticket is published to Realtime');
select is((select count(*)::integer from pg_enum e join pg_type t on t.oid = e.enumtypid where t.typnamespace = 'public'::regnamespace and t.typname = 'TicketStatus' and e.enumlabel = 'EN_STAGING'), 1, 'Ticket status includes staging');
select lives_ok($$select public.create_ticket('Prueba', 'Detalle', 'BUG', null, 'WEB', 'pgTAP', 'test-user', null)$$, 'Atomic create RPC works');
select is((select count(*)::integer from public."TicketActivity" where "actorId" = 'test-user'), 1, 'Create records activity atomically');
select is((select count(*)::integer from public."TicketSyncOutbox" o join public."Ticket" t on t."publicId" = o."ticketPublicId" where t.title = 'Prueba'), 1, 'Create enqueues Discord thread atomically');
select lives_ok($$select public.update_ticket((select "publicId" from public."Ticket" where title = 'Prueba'), '{"status":"EN_STAGING"}'::jsonb, 'WEB', 'pgTAP', 'test-user')$$, 'Ticket can move to staging');
select is((select status::text from public."Ticket" where title = 'Prueba'), 'EN_STAGING', 'Ticket persists staging status');
select is(public.record_discord_interaction('interaction-1', 3), true, 'First interaction is recorded');
select is(public.record_discord_interaction('interaction-1', 3), false, 'Repeated interaction is deduplicated');
select lives_ok($$select public.retry_ticket_sync_job((select o.id from public."TicketSyncOutbox" o join public."Ticket" t on t."publicId" = o."ticketPublicId" where t.title = 'Prueba'), 'Discord 403', null, true)$$, 'Permanent retry is handled');
select is((select o.status::text from public."TicketSyncOutbox" o join public."Ticket" t on t."publicId" = o."ticketPublicId" where t.title = 'Prueba'), 'DEAD_LETTER', 'Permanent 4xx becomes dead letter');
select * from finish();
rollback;
