create extension if not exists pgcrypto;
create extension if not exists pg_cron;
create extension if not exists pg_net;

create type public."TicketType" as enum ('REQUERIMIENTO', 'MEJORA', 'DUDA', 'BUG');
create type public."TicketStatus" as enum ('PENDIENTE', 'EN_PROGRESO', 'EN_ESPERA', 'RESUELTO');
create type public."Platform" as enum ('NESTOR', 'DYLAN', 'ATOM', 'KAYS');
create type public."ActivitySource" as enum ('WEB', 'DISCORD');
create type public."OutboxJobType" as enum ('CREATE_TRIAGE_THREAD', 'SEND_THREAD_MESSAGE', 'ARCHIVE_THREAD');
create type public."OutboxStatus" as enum ('PENDING', 'PROCESSING', 'DELIVERED', 'DEAD_LETTER');

create table public."Ticket" (
  id bigint generated by default as identity primary key,
  "publicId" uuid not null default gen_random_uuid() unique,
  title text not null check (char_length(title) between 1 and 200),
  description text not null check (char_length(description) between 1 and 4000),
  type public."TicketType" not null default 'REQUERIMIENTO',
  status public."TicketStatus" not null default 'PENDIENTE',
  platform public."Platform",
  "createdByName" text not null,
  "createdByDiscordId" text,
  "discordThreadId" text unique,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now()
);

create table public."TicketActivity" (
  id bigint generated always as identity primary key,
  "ticketPublicId" uuid not null,
  source public."ActivitySource" not null,
  action text not null,
  "actorName" text not null,
  "actorId" text,
  changes jsonb not null default '{}'::jsonb,
  "createdAt" timestamptz not null default now()
);

create table public."TicketSyncOutbox" (
  id uuid primary key default gen_random_uuid(),
  "ticketPublicId" uuid not null,
  type public."OutboxJobType" not null,
  payload jsonb not null default '{}'::jsonb,
  status public."OutboxStatus" not null default 'PENDING',
  attempts integer not null default 0 check (attempts between 0 and 8),
  "nextAttemptAt" timestamptz not null default now(),
  "lastError" text,
  "lockedAt" timestamptz,
  "deliveredAt" timestamptz,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now()
);

create table public."DiscordInteraction" (
  id text primary key,
  type integer not null,
  "createdAt" timestamptz not null default now()
);

create index "Ticket_status_idx" on public."Ticket" (status);
create index "Ticket_platform_idx" on public."Ticket" (platform);
create index "Ticket_type_idx" on public."Ticket" (type);
create index "Ticket_updatedAt_idx" on public."Ticket" ("updatedAt" desc);
create index "TicketActivity_ticketPublicId_idx" on public."TicketActivity" ("ticketPublicId", "createdAt" desc);
create index "TicketSyncOutbox_due_idx" on public."TicketSyncOutbox" (status, "nextAttemptAt");

alter table public."Ticket" replica identity full;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new."updatedAt" = now();
  return new;
end;
$$;

create trigger "Ticket_set_updated_at"
before update on public."Ticket"
for each row execute function public.set_updated_at();

create trigger "TicketSyncOutbox_set_updated_at"
before update on public."TicketSyncOutbox"
for each row execute function public.set_updated_at();

create or replace function public.create_ticket(
  p_title text,
  p_description text,
  p_type public."TicketType",
  p_platform public."Platform",
  p_source public."ActivitySource",
  p_actor_name text,
  p_actor_id text default null,
  p_discord_id text default null
)
returns public."Ticket"
language plpgsql
security invoker
set search_path = ''
as $$
declare
  created public."Ticket";
begin
  insert into public."Ticket" (title, description, type, platform, "createdByName", "createdByDiscordId")
  values (p_title, p_description, p_type, p_platform, p_actor_name, p_discord_id)
  returning * into created;

  insert into public."TicketActivity" ("ticketPublicId", source, action, "actorName", "actorId", changes)
  values (created."publicId", p_source, 'CREATED', p_actor_name, p_actor_id, to_jsonb(created));

  insert into public."TicketSyncOutbox" ("ticketPublicId", type, payload)
  values (created."publicId", 'CREATE_TRIAGE_THREAD', jsonb_build_object('ticketPublicId', created."publicId"));

  return created;
end;
$$;

create or replace function public.update_ticket(
  p_public_id uuid,
  p_patch jsonb,
  p_source public."ActivitySource",
  p_actor_name text,
  p_actor_id text default null
)
returns public."Ticket"
language plpgsql
security invoker
set search_path = ''
as $$
declare
  previous public."Ticket";
  changed public."Ticket";
begin
  if p_patch = '{}'::jsonb or p_patch ?| array['publicId', 'id', 'createdByName', 'createdByDiscordId', 'discordThreadId', 'createdAt', 'updatedAt'] then
    raise exception 'Invalid ticket patch';
  end if;

  select * into previous from public."Ticket" where "publicId" = p_public_id for update;
  if not found then raise exception 'Ticket not found'; end if;

  update public."Ticket"
  set
    title = case when p_patch ? 'title' then p_patch->>'title' else title end,
    description = case when p_patch ? 'description' then p_patch->>'description' else description end,
    type = case when p_patch ? 'type' then (p_patch->>'type')::public."TicketType" else type end,
    status = case when p_patch ? 'status' then (p_patch->>'status')::public."TicketStatus" else status end,
    platform = case when p_patch ? 'platform' then nullif(p_patch->>'platform', '')::public."Platform" else platform end
  where "publicId" = p_public_id
  returning * into changed;

  insert into public."TicketActivity" ("ticketPublicId", source, action, "actorName", "actorId", changes)
  values (
    p_public_id,
    p_source,
    'UPDATED',
    p_actor_name,
    p_actor_id,
    jsonb_build_object('before', to_jsonb(previous), 'after', to_jsonb(changed), 'patch', p_patch)
  );

  if p_source = 'WEB' and changed."discordThreadId" is not null then
    insert into public."TicketSyncOutbox" ("ticketPublicId", type, payload)
    values (
      p_public_id,
      'SEND_THREAD_MESSAGE',
      jsonb_build_object(
        'threadId', changed."discordThreadId",
        'content', format('%s El ticket fue actualizado por **%s**.%s%s',
          case when p_source = 'WEB' then '🔄 Desde el tablero Kanban Web.' else '📝 Desde Discord.' end,
          p_actor_name,
          case when p_patch ? 'status' then format(E'\nEstado: **%s**', changed.status) else '' end,
          case when p_patch ? 'platform' then format(E'\nPlataforma: **%s**', coalesce(changed.platform::text, 'Sin asignar')) else '' end
        )
      )
    );
  end if;

  return changed;
end;
$$;

create or replace function public.delete_ticket(
  p_public_id uuid,
  p_source public."ActivitySource",
  p_actor_name text,
  p_actor_id text default null
)
returns public."Ticket"
language plpgsql
security invoker
set search_path = ''
as $$
declare
  removed public."Ticket";
begin
  select * into removed from public."Ticket" where "publicId" = p_public_id for update;
  if not found then raise exception 'Ticket not found'; end if;

  insert into public."TicketActivity" ("ticketPublicId", source, action, "actorName", "actorId", changes)
  values (p_public_id, p_source, 'DELETED', p_actor_name, p_actor_id, jsonb_build_object('ticket', to_jsonb(removed)));

  if removed."discordThreadId" is not null then
    insert into public."TicketSyncOutbox" ("ticketPublicId", type, payload)
    values (
      p_public_id,
      'ARCHIVE_THREAD',
      jsonb_build_object('threadId', removed."discordThreadId", 'content', format('🗑️ Ticket eliminado desde la web por **%s**.', p_actor_name))
    );
  end if;

  delete from public."Ticket" where "publicId" = p_public_id;
  return removed;
end;
$$;

create or replace function public.record_discord_interaction(p_id text, p_type integer)
returns boolean
language plpgsql
security invoker
set search_path = ''
as $$
begin
  insert into public."DiscordInteraction" (id, type) values (p_id, p_type)
  on conflict (id) do nothing;
  return found;
end;
$$;

create or replace function public.set_ticket_discord_thread(p_public_id uuid, p_thread_id text)
returns public."Ticket"
language plpgsql
security invoker
set search_path = ''
as $$
declare changed public."Ticket";
begin
  update public."Ticket" set "discordThreadId" = p_thread_id where "publicId" = p_public_id returning * into changed;
  if not found then raise exception 'Ticket not found'; end if;
  return changed;
end;
$$;

create or replace function public.claim_ticket_sync_jobs(p_limit integer default 10)
returns setof public."TicketSyncOutbox"
language sql
security invoker
set search_path = ''
as $$
  with due as (
    select id from public."TicketSyncOutbox"
    where (status = 'PENDING' or (status = 'PROCESSING' and "lockedAt" < now() - interval '10 minutes'))
      and "nextAttemptAt" <= now()
      and attempts < 8
    order by "createdAt"
    for update skip locked
    limit greatest(1, least(p_limit, 50))
  )
  update public."TicketSyncOutbox" jobs
  set status = 'PROCESSING', "lockedAt" = now(), attempts = attempts + 1
  from due
  where jobs.id = due.id
  returning jobs.*;
$$;

create or replace function public.complete_ticket_sync_job(p_id uuid)
returns void
language sql
security invoker
set search_path = ''
as $$
  update public."TicketSyncOutbox"
  set status = 'DELIVERED', "deliveredAt" = now(), "lockedAt" = null, "lastError" = null
  where id = p_id;
$$;

create or replace function public.retry_ticket_sync_job(
  p_id uuid,
  p_error text,
  p_retry_after_seconds integer default null,
  p_permanent boolean default false
)
returns void
language plpgsql
security invoker
set search_path = ''
as $$
declare current_attempts integer;
begin
  select attempts into current_attempts from public."TicketSyncOutbox" where id = p_id for update;
  update public."TicketSyncOutbox"
  set
    status = case when p_permanent or current_attempts >= 8 then 'DEAD_LETTER'::public."OutboxStatus" else 'PENDING'::public."OutboxStatus" end,
    "lastError" = left(p_error, 1000),
    "lockedAt" = null,
    "nextAttemptAt" = now() + make_interval(secs => coalesce(p_retry_after_seconds, least(3600, power(2, current_attempts)::integer * 30)))
  where id = p_id;
end;
$$;

alter table public."Ticket" enable row level security;
alter table public."TicketActivity" enable row level security;
alter table public."TicketSyncOutbox" enable row level security;
alter table public."DiscordInteraction" enable row level security;

revoke all on table public."Ticket", public."TicketActivity", public."TicketSyncOutbox", public."DiscordInteraction" from anon, authenticated;
grant select on table public."Ticket", public."TicketActivity" to authenticated;

create policy "Authenticated users can read tickets"
on public."Ticket" for select to authenticated using (true);

create policy "Authenticated users can read ticket activities"
on public."TicketActivity" for select to authenticated using (true);

revoke all on function public.create_ticket(text, text, public."TicketType", public."Platform", public."ActivitySource", text, text, text) from public, anon, authenticated;
revoke all on function public.update_ticket(uuid, jsonb, public."ActivitySource", text, text) from public, anon, authenticated;
revoke all on function public.delete_ticket(uuid, public."ActivitySource", text, text) from public, anon, authenticated;
revoke all on function public.record_discord_interaction(text, integer) from public, anon, authenticated;
revoke all on function public.set_ticket_discord_thread(uuid, text) from public, anon, authenticated;
revoke all on function public.claim_ticket_sync_jobs(integer) from public, anon, authenticated;
revoke all on function public.complete_ticket_sync_job(uuid) from public, anon, authenticated;
revoke all on function public.retry_ticket_sync_job(uuid, text, integer, boolean) from public, anon, authenticated;

grant execute on function public.create_ticket(text, text, public."TicketType", public."Platform", public."ActivitySource", text, text, text) to service_role;
grant execute on function public.update_ticket(uuid, jsonb, public."ActivitySource", text, text) to service_role;
grant execute on function public.delete_ticket(uuid, public."ActivitySource", text, text) to service_role;
grant execute on function public.record_discord_interaction(text, integer) to service_role;
grant execute on function public.set_ticket_discord_thread(uuid, text) to service_role;
grant execute on function public.claim_ticket_sync_jobs(integer) to service_role;
grant execute on function public.complete_ticket_sync_job(uuid) to service_role;
grant execute on function public.retry_ticket_sync_job(uuid, text, integer, boolean) to service_role;

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'Ticket'
  ) then
    alter publication supabase_realtime add table public."Ticket";
  end if;
end;
$$;
